package com.smsguard.update

import android.util.Base64
import java.security.KeyFactory
import java.security.PublicKey
import java.security.Signature
import java.security.spec.X509EncodedKeySpec

object SignatureVerifier {
    // Hardcoded Public Key (Ed25519 DER/SPKI base64)
    // Generated by scripts/generate_keys.py (from rules/public_key.txt)
    private const val PUBLIC_KEY_BASE64 = "MCowBQYDK2VwAyEAvlyDRN3so8NZlL49jxDyMYtLvm08v12dCxZElWsHj50="

    fun verifyEd25519(messageBytes: ByteArray, signatureBytes: ByteArray): Boolean {
        return try {
            val keyBytes = Base64.decode(PUBLIC_KEY_BASE64, Base64.DEFAULT)
            val spec = X509EncodedKeySpec(keyBytes)
            val kf = KeyFactory.getInstance("Ed25519")
            val publicKey: PublicKey = kf.generatePublic(spec)

            val sig = Signature.getInstance("Ed25519")
            sig.initVerify(publicKey)
            sig.update(messageBytes)
            sig.verify(signatureBytes)
        } catch (e: Exception) {
            false
        }
    }

    @Deprecated("Use verifyEd25519(messageBytes, signatureBytes)")
    fun verify(data: ByteArray, signatureBytes: ByteArray): Boolean =
        verifyEd25519(messageBytes = data, signatureBytes = signatureBytes)
}
