# ProGuard / R8 rules for SMS_Seguro
# ----------------------------------------------------------

# ---- kotlinx-serialization ----
# Keep serializer classes generated by the compiler plugin.
# Without these, Json.decodeFromString / encodeToString crash at runtime.
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**

# Keep the companion object serializers ($serializer, Companion)
-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep every @Serializable class and its generated $serializer
-keepclassmembers @kotlinx.serialization.Serializable class com.smsguard.** {
    *** Companion;
    *** INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}
-keepclasseswithmembers class com.smsguard.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep enum entries used in @Serializable enums (RiskLevel, AlertType)
-keepclassmembers enum com.smsguard.** {
    <fields>;
}

# ---- OkHttp ----
# OkHttp bundles its own consumer rules, but keep platform adapters
# in case R8 strips them on certain API levels.
-dontwarn okhttp3.internal.platform.**
-dontwarn org.bouncycastle.**
-dontwarn org.conscrypt.**
-dontwarn org.openjsse.**

# ---- AndroidX WorkManager ----
# WorkManager uses reflection to instantiate workers.
-keep class com.smsguard.update.RuleUpdateWorker { *; }

# ---- AndroidX Startup / Services ----
# Foreground service and receivers instantiated by the system.
-keep class com.smsguard.startup.SmsProtectionService { *; }
-keep class com.smsguard.startup.BootReceiver { *; }
-keep class com.smsguard.notification.SmsNotificationListener { *; }
